### ISSUE TITLE
WorldEditSlimefun failed to load due to bstats metrics class

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/WorldEditSlimefun#5]
See the error from console.

[19:58:57 INFO]: [WorldEditSlimefun] Enabling WorldEditSlimefun vDev - 3
[19:58:57 ERROR]: Error occurred while enabling WorldEditSlimefun vDev - 3 (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
        at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:251) ~[WorldEditSlimefun.jar:?]
        at org.bstats.MetricsBase.<init>(MetricsBase.java:121) ~[WorldEditSlimefun.jar:?]
        at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[WorldEditSlimefun.jar:?]
        at dev.j3fftw.worldeditslimefun.WorldEditSlimefun.onEnable(WorldEditSlimefun.java:43) ~[WorldEditSlimefun.jar:?]        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-169]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-169]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-169]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-169]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:58:57 INFO]: [WorldEditSlimefun] Disabling WorldEditSlimefun vDev - 3

**Comment by JustAHuman-xD** [comment]
Yep, this is fixed by the PR I have open

**Comment by WalshyDev** [comment]
@JustAHuman-xD can you move it into a sole PR? PRs with a single focus is good

**Comment by JustAHuman-xD** [comment]
> @JustAHuman-xD can you move it into a sole PR? PRs with a single focus is good

Sure!
